### ISSUE TITLE
[BUG]: FIGHT : 🐏 Attaque bélier 

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#1756]
### Description du bug.

Lorsqu'il est sous altération d'était affaibli, le paladin ne reçoit plus de contrecoup lors de la réalisation de l'attaque bélier.

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

En combat : 
- J-1 (tank) : attaque bouclier
- J-2 (pala) : attaque bélier
=> on constate alors que le paladin n'a pas pris de contrecoup

### Captures d'écran

![DF111372-6DD0-4DA6-BB39-484F74301FEE](https://user-images.githubusercontent.com/80409766/213031089-0618152d-02a4-4bcb-bafc-cd4b868a7477.jpeg)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
Je crois pas que ce soit un bug

**Comment by BastLast** [comment]
Ici orion est affaibli donc il a déjà une altération d'État donc il veut pas en avoir une deuxième

**Comment by BastLast** [comment]
L'attaque bélier elle donne soit un contre coup soit elle peut te rendre confus toi-même et là en l'occurrence je pense qu'il a eu le cas où il a été rendu confus lui-même sauf que vu qu'il était déjà affaibli et ben il a rien eu et du coup ça continue sans avoir de contrecoup il a juste eu de la chance et pour moi c'est pas un bug

**Comment by BastLast** [comment]
À chaque fois qu'on donne une altération d'État un joueur si il en a déjà une on annule ça c'est la règle universelle pour tous les fight c'est une discussion qui pour une décision qui pourrait être débattu mais elle a été mise en place comme ça je pense qu'elle apporte des éléments stratégiques intéressants et je pense que ce serait pas une bonne idée de rajouter des incohérences là-dedans et de changer son comportement dans certaines situations donc je pense que ça va rester comme ça je ferme donc cette issue en dans le cas note planète because je pense que c'est pas un bug mais si vous allez fouiller le code et qui s'avère que ce que j'ai dit ici c'est pas vrai goélard ouvrir mais je suis à peu près sûr de moi 90 %

**Comment by BastLast** [comment]
En fait le problème c'est que le truc est récurrent c'est à dire que à chaque fois que il y a plus qu'une altération de l'état pour le mec qui a fait la tête bélier il a pas de contrecoup c'est à chaque fois donc ma théorie ci-dessus ne tient pas

**Comment by Feiryn** [comment]
Les tests ont montré qu'il n'y a pas de bug il y a juste une chance, si l'attaquant a un effet ,qu'il ne recoive pas les degats, c'est pas systématique
