### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by royalus** [DraftBot-A-Discord-Adventure/DraftBot#325]
![Untitled](https://user-images.githubusercontent.com/59321692/107861207-f8763b80-6e4c-11eb-9fcf-2b0a56e24023.png)

**Comment by eagles666** [comment]
Bonsoir,

Ce problème vient du fait que votre bot n'as pas les permissions requises pour fonctionner correctement. Cela n'est pas de notre ressort.

Je me permets donc de vous renvoyer vers https://discordjs.guide/popular-topics/permissions-extended.html#missing-permissions afin de résoudre votre problème.

-----

Good evening,

This problem stems from the fact that your bot does not have the required permissions to function properly. This is not our responsibility.

I therefore allow myself to refer you to https://discordjs.guide/popular-topics/permissions-extended.html#missing-permissions in order to resolve your problem.

**Comment by BastLast** [comment]
Hello and thx @eagles666 for the reply. For further help, please use the bot's discord server.

**Comment by royalus** [comment]
another question how to fix this ?
![Untitled](https://user-images.githubusercontent.com/59321692/107862893-bd7a0500-6e58-11eb-9187-e08d897d79df.png)
